events {}

http {
  upstream servidores {
    server servidor_1:8080;
    server servidor_2:8080;
    server servidor_3:8080;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://servidores;
    }
  }
}